### ISSUE TITLE
Please use semantic versioning

### ISSUE THREAD

**Issue by petercolberg** [jmhodges/clock#3]
Please use semantic versioning:
- http://semver.org/
- https://en.wikipedia.org/wiki/Software_versioning
- https://wiki.debian.org/UpstreamGuide#Releases_and_Versions

**Comment by jmhodges** [comment]
What API break where you burned by and when?

**Comment by jmhodges** [comment]
("What API break this library", I mean)

**Comment by petercolberg** [comment]
It would make distribution packaging of your software much more convenient if you could tag releases.

**Comment by jmhodges** [comment]
Are you doing that? What for?

You're fine with just some tags? Does it need to work with the go tool?

**Comment by jmhodges** [comment]
Oh, hope I didn't come off as brusque. Just want to understand exactly what you want. The original issue isn't enough to go off of.

**Comment by petercolberg** [comment]
Debian packages each Go package repository as a separate Debian source package. In this case, your package has been [included in Debian](https://packages.debian.org/sid/golang-github-jmhodges-clock-dev) as a dependency of [acmetool](https://github.com/hlandau/acme). The version of a Debian package includes an upstream part (e.g. "1.0.0") and a Debian part (e.g. "-1"). If an upstream author does not tag releases, we need to make up an upstream version number based on the git commit and date, which yields unwieldy versions that are cumbersome to compare. 

All you would have to do is regularly tag releases, which yields handy Debian package versions and makes it easy to automatically [notice new upstream releases](https://tracker.debian.org/pkg/golang-gopkg-tylerb-graceful.v1) using the Debian package tracker.

**Comment by jmhodges** [comment]
Done. Thanks!

**Comment by petercolberg** [comment]
Thanks! A small detail: For semantic versioning you probably want to start with `v1.0.0` for the first tag.
