### ISSUE TITLE
Semantic versioning

### ISSUE THREAD

**Issue by pboguslawski** [jmhodges/clock#7]
Please use semantic versioning (i.e. v1.1.0 not just v1.1) in tags like in

https://github.com/jmhodges/clock/issues/3#issuecomment-205137227
https://go.dev/ref/mod

Without it go module updating cmd cannot find latest version and generate pseudo-versions like

```
github.com/jmhodges/clock v0.0.0-20160418191101-880ee4c33548 [v0.0.0-20211218015646-21de17d65b1b]
```

**Comment by jmhodges** [comment]
Published a v1.2.0
